env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules: 
  array-bracket-spacing: [error, always]
  quotes: off
  semi: off
  "@typescript-eslint/semi": [error, always]
  "@typescript-eslint/quotes": [error, single]
  "@typescript-eslint/consistent-type-imports": warn
  "@typescript-eslint/no-confusing-void-expression": off
  "@typescript-eslint/promise-function-async": warn
