version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    networks:
      - todo-app-network

  mongodb:
    build: ./mongodb
    ports:
      - 60000:27017
    volumes:
      - ./mongodb/create-schema.js:/docker-entrypoint-initdb.d/create-schema.js:ro # ro - read-only
    restart: unless-stopped
    networks:
      - todo-app-network
  
  backend:
    depends_on:
      - mongodb
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge