version: '3'

services:

  todo-mongo:
    container_name: todo-mongo
    image: mongo
    ports:
      - 60000:27017
    volumes:
      - ./create-schema.js:/docker-entrypoint-initdb.d/create-schema.js:ro # ro - read-only
    restart: unless-stopped
